PXC-4221: PXC 8.0.33 refresh - Q2 2023
https://jira.percona.com/browse/PXC-4221

Fixed compilation errors for gcc-12.

--Wstringop-overflow specified bound 18446744073709551615 exceeds
maximum object size 9223372036854775807
was caused by compiler detecting possibly negative number passed to
std::copy()

error: '__builtin_strncpy' output may be truncated copying 12 bytes from
a string of length 20 [-Werror=stringop-truncation]
was caused by obvious truncation of the string.